# **Exercícios Numpy**

In [1]:
import numpy as np

In [2]:
vetor = np.array([0, 2, 4])

In [4]:
mat = np.array([[0, 2, 4], [1, 2, 4], [1, 2, 4] ])
mat

array([[0, 2, 4],
       [1, 2, 4],
       [1, 2, 4]])

In [5]:
mat.shape

(3, 3)

In [6]:
lista1 = [0, 1, 2]
lista2 = [3, 4, 5]
lista3 = [6, 7, 8]

In [7]:
mat = np.array = ([lista1,lista2,lista3])

In [8]:
np.arange(40, 100, 2)

array([40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72,
       74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [14]:
vetor = np.arange(10)
vetor

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
vetor ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])