# **Numpy**

Segundo a [documentação oficial](https://numpy.org/doc/), NumPy é um pacote para computação científica em Python.  

---
## **Instalação**


A instalação do pocote pode ser feita usando um dos comandos abaixo: 

- `conda install numpy`, caso utilize o [Anaconda](https://www.anaconda.com/) 
- `pip install numpy`, caso contrário 

---
## **Importando o NumPy**

In [2]:
# Importando o Numpy:

# ---
# seu código vai aqui
#---

---
## **Numpy Arrays**

**Para criar um numpy array podemos declarar uma lista e utilizá-la como parâmetro para a função array():**

In [3]:
#lista 1

# ---
# seu código vai aqui
#---

In [4]:
# array 1

# ---
# seu código vai aqui
#---

💡 **Note que podemos criar uma matriz a partir de um cojunto de listas ou de arrays:**

In [5]:
# matriz gerada a partir das listas 1

# ---
# seu código vai aqui
#---

In [6]:
# matriz gerada a partir das listas 2

# ---
# seu código vai aqui
#---

In [7]:
# matriz gerada a partir dos arrays 1

# ---
# seu código vai aqui
#---


---
## **Inicializando valores dos arrays**

Funções para criar e inicializar arrays: 
- `arange()`
- `zeros()`
- `ones()`
- `linspace()` 
- `eye()`

---
### 👉 **arange()**

**Cria uma sequência de números entre um valor inicial, um valor final. Note que os valores intermediários podem ter o valor de incremento personalizado:**  

In [8]:
# Consulte a documentação:

# ---
# seu código vai aqui
#---

**Como pode ser visto na documentação, a sintaxe esperada é:**  
- `a = np.arange(inicio, fim, passo)`

In [9]:
# Crie um array com 10 elementos:

# ---
# seu código vai aqui
#---

💡 **Note que o primeiro valor "0" está incluído no array e que o último valor "10" não é incluído.**

In [10]:
# Crie um array com os múmeros pares de 0 até 10

# ---
# seu código vai aqui
#---

---
### 👉 **zeros() e ones()**

**Criam arrays contendo apenas valores iguais a 0 (zero) ou 1 (um), respectivamente.**  
**As sintaxes esperadas são:**   
- `a = np.zeros((dim1, dim2, dim3, ...))`  
- `b = np.ones((dim1, dim2, dim3, ...))`

In [11]:
# criar um array com três elementos 0

# ---
# seu código vai aqui
#---

In [12]:
# criar uma matriz 5x5 preenchida com elementos 0

# ---
# seu código vai aqui
#---

In [13]:
# criar um array com três elementos 1

# ---
# seu código vai aqui
#---

In [14]:
# criar uma matriz 3x3 preenchida com elementos 1

# ---
# seu código vai aqui
#---

---
### 👉 **linspace()**

**Cria valores igualmente espaçados em um determinado intervalo.**   
**A sintaxe esperada é:**   
- `a = np.linspace(inicio, fim, quantidade)`

In [15]:
# criar uma sequencia de 3 números entre 0 e 10, igualmente espaçados entre si:

# ---
# seu código vai aqui
#---

In [16]:
# criar uma sequencia de 15 números entre 0 e 10, igualmente espaçados entre si:

# ---
# seu código vai aqui
#---

---
### 👉 **eye()**

**Cria uma matriz identidade, ou seja, uma matriz cuja diagonal principal tem valores 1, e todos os outros valores são 0.**  
**A sintaxe esperada é:**   
- `a = np.eye(dimensão)`

In [17]:
# criar uma matriz identidade de dimensões 4x4:

# ---
# seu código vai aqui
#---

---
## **Atributos e métodos de arrays**

**São funções e atributos intrínsicos dos arrays, considerados dados internos. Vejamos alguns exemplos a seguir.**

---
### 👉 **reshape()**

**Altera as dimensões de um array, desde que as dimensões inicias e finais sejam compatíveis.**  
**A sintaxe esperada é:**   
- `a.reshape((dim1, dim2, dim3, ...))` 

In [18]:
# cria um array de 25 elementos:

# ---
# seu código vai aqui
#---

In [19]:
# redimensiona o array para um matriz de dimensoes 5x5:

# ---
# seu código vai aqui
#---

---
### 👉 **max()**, **min()**, **argmax()** e **argmin()**

**Retornam os valores máximo, mínimo, o índice do valor máximo e índice do valor mínimo de um array, respectivamete.**

In [20]:
#cria um array com valores aleatórios

# ---
# seu código vai aqui
#---

In [21]:
#informa o valor máximo do array

# ---
# seu código vai aqui
#---

In [22]:
#informa o indice do elemento de valor máximo do array, ou seja, a posição que ele ocupa no array

# ---
# seu código vai aqui
#---

In [23]:
#informa o valor mínimo do array

# ---
# seu código vai aqui
#---

In [24]:
#informa o indice do elemento de valor mínimo do array, ou seja, a posição que ele ocupa no array

# ---
# seu código vai aqui
#---

---
### 👉 **shape**

**É uma tupla que armazena as dimensões do array**

In [26]:
# ---
# seu código vai aqui
#---

In [27]:
# ---
# seu código vai aqui
#---

---
### 👉 **dtype()**

**Informa qual é o tipo de variável dos elementos do array**

In [28]:
# ---
# seu código vai aqui
#---

In [29]:
# ---
# seu código vai aqui
#---

---
## **Seleção e indexação de numpy arrays**

---
### 👉 **Seleção por chaves**

Possibilita selecionar um ou mais elementos de um array

In [30]:
# cria um array

# ---
# seu código vai aqui
#---

In [31]:
# mostra o elemento da 5a posição

# ---
# seu código vai aqui
#---

In [32]:
# mostra os elementos do intervalo desde até o segundo elemento até o quinto elemento
# note que o segundo elemento é incluído e o quinto elemento não é incluído

# ---
# seu código vai aqui
#---

In [33]:
# ---
# seu código vai aqui
#---

---
### 👉 ***Broadcasting***

Realiza as operações elemento a elemento

In [44]:
# cria um array

# ---
# seu código vai aqui
#---

[0 1 2 3 4 5 6 7 8 9]


In [45]:
# soma realizada elemento a elemento

# ---
# seu código vai aqui
#---

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [46]:
# multiplicação realizada elemento a elemento

# ---
# seu código vai aqui
#---

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [47]:
# subtração realizada elemento a elemento

# ---
# seu código vai aqui
#---

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [48]:
# divisão realizada elemento a alemento 
# note que a divisão por zero gera um aviso e seu resultado é um NaN

# ---
# seu código vai aqui
#---

/tmp/ipykernel_11927/3494184251.py:3: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [49]:
# exponenciação elemento a elemento

# ---
# seu código vai aqui
#---

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

---
# 🥳🥳🥳 Bom trabalho!